spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: Hanhan65
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true